//! Direct NSPasteboard access (read + write) via objc2.
use objc2::rc::Retained;
use objc2::AnyThread;
use objc2::runtime::ProtocolObject;
use objc2_app_kit::{
    NSPasteboard, NSPasteboardTypeFileURL, NSPasteboardTypeHTML, NSPasteboardTypePNG,
    NSPasteboardTypeRTF, NSPasteboardTypeString, NSPasteboardTypeTIFF, NSPasteboardWriting,
};
use objc2_foundation::{NSArray, NSData, NSString, NSURL};
use std::path::{Path, PathBuf};

/// Custom type stamped on everything Paste writes so the monitor can recognize its own writes.
pub const SELF_MARKER: &str = "io.paste.rs.marker";
const CONCEALED: &str = "org.nspasteboard.ConcealedType";
const TRANSIENT: &str = "org.nspasteboard.TransientType";
const AUTOGENERATED: &str = "org.nspasteboard.AutoGeneratedType";

#[derive(Debug)]
pub enum Content {
    Files(Vec<PathBuf>),
    Image { data: Vec<u8>, is_png: bool },
    Text { text: String, rtf: Option<Vec<u8>>, html: Option<String> },
}

#[derive(Debug)]
pub struct Snapshot {
    pub content: Option<Content>,
    pub concealed: bool,
    pub transient: bool,
    pub self_marker: Option<i64>,
}

pub fn change_count() -> isize {
    NSPasteboard::generalPasteboard().changeCount()
}

fn has_type(types: &[String], t: &str) -> bool {
    types.iter().any(|x| x == t)
}

pub fn read() -> Snapshot {
    let pb = NSPasteboard::generalPasteboard();
    let types: Vec<String> = pb
        .types()
        .map(|arr| arr.iter().map(|t| t.to_string()).collect())
        .unwrap_or_default();

    let self_marker = pb
        .stringForType(&NSString::from_str(SELF_MARKER))
        .and_then(|s| s.to_string().parse::<i64>().ok());
    let concealed = has_type(&types, CONCEALED);
    let transient = has_type(&types, TRANSIENT) || has_type(&types, AUTOGENERATED);

    let mut content = None;

    // Files first: Finder copies carry file URLs plus icons/strings we don't want.
    let file_url_type = unsafe { NSPasteboardTypeFileURL };
    if has_type(&types, &file_url_type.to_string()) {
        let mut files = Vec::new();
        if let Some(items) = pb.pasteboardItems() {
            for item in items.iter() {
                if let Some(s) = item.stringForType(file_url_type) {
                    if let Some(url) = NSURL::URLWithString(&s) {
                        if let Some(p) = url.path() {
                            files.push(PathBuf::from(p.to_string()));
                        }
                    }
                }
            }
        }
        if !files.is_empty() {
            content = Some(Content::Files(files));
        }
    }

    if content.is_none() {
        let png_t = unsafe { NSPasteboardTypePNG };
        let tiff_t = unsafe { NSPasteboardTypeTIFF };
        let string_t = unsafe { NSPasteboardTypeString };
        let has_png = has_type(&types, &png_t.to_string());
        let has_tiff = has_type(&types, &tiff_t.to_string());
        let has_string = has_type(&types, &string_t.to_string());
        // Some apps put a short caption (image URL / file name) next to the bitmap; in that
        // case the bitmap is what the user wanted. Real text selections are longer or contain
        // whitespace and win over an incidental image.
        let string_is_caption = has_string
            && pb
                .stringForType(string_t)
                .map(|s| {
                    let s = s.to_string();
                    let t = s.trim();
                    t.len() < 2048 && (crate::util::looks_like_url(t) || !t.contains(char::is_whitespace))
                })
                .unwrap_or(false);
        if (has_png || has_tiff) && (!has_string || string_is_caption) {
            if has_png {
                if let Some(d) = pb.dataForType(png_t) {
                    content = Some(Content::Image { data: d.to_vec(), is_png: true });
                }
            }
            if content.is_none() && has_tiff {
                if let Some(d) = pb.dataForType(tiff_t) {
                    content = Some(Content::Image { data: d.to_vec(), is_png: false });
                }
            }
        }
        if content.is_none() && has_string {
            if let Some(s) = pb.stringForType(string_t) {
                let text = s.to_string();
                let rtf = if has_type(&types, &unsafe { NSPasteboardTypeRTF }.to_string()) {
                    pb.dataForType(unsafe { NSPasteboardTypeRTF }).map(|d| d.to_vec())
                } else {
                    None
                };
                let html = if has_type(&types, &unsafe { NSPasteboardTypeHTML }.to_string()) {
                    pb.stringForType(unsafe { NSPasteboardTypeHTML }).map(|s| s.to_string())
                } else {
                    None
                };
                content = Some(Content::Text { text, rtf, html });
            }
        }
        // Image with an accompanying string (e.g. Preview copies "image.png" as string): take the image
        if content.is_none() && (has_png || has_tiff) {
            let t = if has_png { png_t } else { tiff_t };
            if let Some(d) = pb.dataForType(t) {
                content = Some(Content::Image { data: d.to_vec(), is_png: has_png });
            }
        }
    }

    Snapshot { content, concealed, transient, self_marker }
}

pub enum WriteItem<'a> {
    Text(&'a str),
    Rich { text: &'a str, rtf: Option<&'a [u8]>, html: Option<&'a str> },
    Image { png: &'a [u8] },
    Files(&'a [PathBuf]),
}

/// Writes an item to the general pasteboard and stamps it with our marker.
/// Returns the new change count.
pub fn write(item: WriteItem, marker_id: i64) -> isize {
    let pb = NSPasteboard::generalPasteboard();
    pb.clearContents();
    match item {
        WriteItem::Text(text) => {
            pb.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString });
        }
        WriteItem::Rich { text, rtf, html } => {
            if let Some(rtf) = rtf {
                pb.setData_forType(Some(&NSData::with_bytes(rtf)), unsafe { NSPasteboardTypeRTF });
            }
            if let Some(html) = html {
                pb.setString_forType(&NSString::from_str(html), unsafe { NSPasteboardTypeHTML });
            }
            pb.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString });
        }
        WriteItem::Image { png } => {
            pb.setData_forType(Some(&NSData::with_bytes(png)), unsafe { NSPasteboardTypePNG });
            // TIFF is only needed by a few legacy apps; converting large images would stall pasting.
            if png.len() <= 3 * 1024 * 1024 {
                if let Some(tiff) = png_to_tiff(png) {
                    pb.setData_forType(Some(&NSData::with_bytes(&tiff)), unsafe { NSPasteboardTypeTIFF });
                }
            }
        }
        WriteItem::Files(paths) => {
            let existing: Vec<&PathBuf> = paths.iter().filter(|p| p.exists()).collect();
            let urls: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> = existing
                .iter()
                .map(|p| {
                    let url = NSURL::fileURLWithPath(&NSString::from_str(&p.to_string_lossy()));
                    ProtocolObject::from_retained(url)
                })
                .collect();
            if !urls.is_empty() {
                let arr = NSArray::from_retained_slice(&urls);
                pb.writeObjects(&arr);
            }
            let names: Vec<String> = existing.iter().map(|p| p.to_string_lossy().to_string()).collect();
            pb.setString_forType(&NSString::from_str(&names.join("\n")), unsafe { NSPasteboardTypeString });
        }
    }
    pb.setString_forType(&NSString::from_str(&marker_id.to_string()), &NSString::from_str(SELF_MARKER));
    pb.changeCount()
}

fn png_to_tiff(png: &[u8]) -> Option<Vec<u8>> {
    use objc2_app_kit::NSImage;
    let data = NSData::with_bytes(png);
    let image = NSImage::initWithData(NSImage::alloc(), &data)?;
    image.TIFFRepresentation().map(|d| d.to_vec())
}

pub fn file_name(p: &Path) -> String {
    p.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default()
}
